# SonarQube Configuration
sonar.projectKey=fiap-challenge-13soat_mecanica-hermes-api
sonar.organization=fiap-challenge-13soat

# Source and test paths
sonar.sources=src
sonar.tests=tests

# Exclusions
sonar.exclusions=**/bin/**,**/obj/**,coverage-report/**,**/Migrations/**
sonar.test.inclusions=tests/**

# Coverage
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

# Disable specific rules
sonar.issue.ignore.multicriteria=e1,e2,e3

# S107: Methods should not have too many parameters
sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S107
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*

# S1118: Utility classes should not have public constructors (for static DbSet properties - false positive)
sonar.issue.ignore.multicriteria.e2.ruleKey=csharpsquid:S1118
sonar.issue.ignore.multicriteria.e2.resourceKey=**/AppDbContext.cs

# S2094: Classes should not be empty (for IEntityTypeConfiguration - false positive)
sonar.issue.ignore.multicriteria.e3.ruleKey=csharpsquid:S2094
sonar.issue.ignore.multicriteria.e3.resourceKey=**/Configurations/*.cs
